# Use 32bit for both Raspberry Pi 3 and 4
FROM balenalib/raspberrypi3-debian:stretch

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
ENV UDEV=1

RUN install_packages \
  alsa-utils \
  bluealsa \
  bluez

COPY start.sh /usr/src/
RUN chmod +x /usr/src/start.sh

CMD [ "/bin/bash", "/usr/src/start.sh" ]
